# Prepare the base os

# Get latest package info and install updates

- name: get updates, long running process (~5mins)
  apt:
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: upgrade packages, long running process (~5mins)
  apt:
    upgrade: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Install dos2unix in case any files have Windows EOL characters
  apt:
    name: dos2unix

- name: install git
  apt:
    name: git

# Download metomivms data from github
- name: download metomi-vm-files from github
  git:
    repo: https://github.com/metomi/metomi-vms.git
    dest: /home/{{ username }}/metomi-vms
    force: yes
  register: git_deploy
  until: git_deploy is success
  become: yes
  become_user: "{{ username }}"
