- name: symlink /home/ubuntu to /home/vagrant
  file:
    src: /home/{{ username }}
    dest: /home/{{ vagrant }}
    state: link
    force: yes

# Make $UMDIR
- name: make UMDIR
  file:
    path: /home/{{ vagrant }}/umdir
    state: directory
    mode: 0755

# Make $UMDIR/bin
- name: make UMDIR/bin
  file:
    path: /home/{{ vagrant }}/umdir/bin
    state: directory
    mode: 0755

- name: Download & install Xconv to UMDIR/bin
  unarchive:
    src: http://cms.ncas.ac.uk/documents/xconv/_downloads/xconv1.94_linux_x86_64.tar.gz
    dest: /home/{{ vagrant }}/umdir/bin
    remote_src: yes

- name: link xconv1.94 to xconv
  file:
    src: /home/{{ vagrant }}/umdir/bin/xconv1.94
    dest: /home/{{ vagrant }}/umdir/bin/xconv
    state: link
    force: yes

- name: link xconv1.94 to convsh
  file:
    src: /home/{{ vagrant }}/umdir/bin/xconv1.94
    dest: /home/{{ vagrant }}/umdir/bin/convsh
    state: link
    force: yes
