---
- hosts: ukca_vm
  remote_user: "{{ username }}"
  become: true
  become_method: sudo
  gather_facts: False
  pre_tasks:
    - name: install python2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)


  roles:
    - role: configure-os
    - role: download-xconv
    - role: install-base
    - role: install-desktop
    - role: install-um-extras
    - role: install-mosrs

  handlers:
  - name: Restart ssh
    service: name=ssh state=restarted
