region_name: 'eu-west-2'
key_name: 'ukca_keypair'
ami_id: 'ami-0be590cb7a2969726' # Ubuntu 18.04 64-bit CPU in eu-west-2
instance_type: 't2.large' # 2xCPU/8xGB memory
instance_name: 'ukca_vm'
volumes:
  - device_name: /dev/sda1
    volume_size: 50 # 50GB disk
    # remove volume when EC2 instance terminated - if not included
    # volume will persist and need to be deleted manually
    delete_on_termination: yes
