# INSTALL NECESSARY ADDITIONS FOR USING THE NVIDIA HPC SDK WITH THE UM

# install packages for using the NVIDIA compiler with the UM and to be able to compile the UM with NVIDIA
# also install the NVIDIA driver (which also provides nvidi-smi) to allow the user to access the graphics card
- name: install additional required packages for NVIDIA
  apt:
    pkg: 
    - environment-modules
    - libnuma-dev
    - nvidia-driver-495

# install pre-made .deb file for the netcdf4 libraries built using NVHPC SDK v22.1
- name: Install netCDF4 pre-build using NVIDIA HPC SDK v22.1
  apt:
    deb: https://gws-access.jasmin.ac.uk/public/ukca/nvidia-netcdf_4.5.4-1_amd64.deb

# need to enable use of nvhpc modules in .bashrc
# will only work once the NVHPC modules are available for use
- name: Update .bashrc with modulefile
  blockinfile:
    block: "{{ lookup('file', 'bashrc_nvidia') }}"
    path: /home/{{ username }}/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK NVIDIA"

# The user will need to install the NVHPC .deb files from here
# https://developer.nvidia.com/nvidia-hpc-sdk-downloads 
# as they will need to manually accept licence agreement prior to download
# It is recommended to use version 22.1 as this has been tested with the UM, GCOM, & SHUMLIB
# and was used to compile up the netCDF4 libraries used in the .deb file above